### PR TITLE
fixed the bug in PolyEval

### LINKED ISSUE #192: bug in genrating Random Linear Combination of expressions and extracting the assignment.
## Impact
__environment [Testnet/Mainnet]__

__an user is impacted [Y/N], if yes type of user: [External/Internal]__

## Describe the bug 
for special edge cases, one of the following functions is not working correctly.

`func RandLinCombColSymbolic(x coin.Info, hs []ifaces.Column) *symbolic.Expression {}`

` func EvalExprColumn(run *wizard.ProverRuntime, board symbolic.ExpressionBoard) smartvectors.SmartVector {}`

### Steps to Reproduce
for the moment, we are not able to reproduce the bug independently via, e.g., test cases. it shows itself when running
`func TestSelfRecursionMultiLayered(t *testing.T) {}`.

This bug is temporality ignored by replacing the original function

```
func RandLinCombColSymbolic(x coin.Info, hs []ifaces.Column) *symbolic.Expression {
	cols := make([]*symbolic.Expression, len(hs))
	for c := range cols {
		cols[c] = ifaces.ColumnAsVariable(hs[c])
	}
	expr := symbolic.NewPolyEval(x.AsVariable(), cols)
	return expr
}
```
With what is supposed to be equivalent as
```
func RandLinCombColSymbolic(x coin.Info, hs []ifaces.Column) *symbolic.Expression {
	res := symbolic.NewConstant(0)
	for i := len(hs) - 1; i >= 0; i-- {
		res = symbolic.Mul(res, x)
		res = symbolic.Add(res, hs[i])
	}
	return res
}
```

### more cases
 also, check the test  `TestInnerProduct()` that is not working alongside symbolic.NewPolyEval()
 see  https://github.com/Consensys/linea-monorepo/blob/main/prover/protocol/compiler/innerproduct/context.go

### Actual result/Expected result
swapping the mentioned function should not affect the tests, as they are expected to be equivalent. However, some tests do not pass the original function.

### PR DESCRIPTION
**Pull request by Soleimani193**
This PR  solves issue #192 for the case of PolyEval over Product and also  PolyEval over PolyEval happening in the inner-product compiler and selfrecursion. For the product operator Product.Evaluate()  outputs *Pooled type that was not supported as input to PolyEval. 

close #192 

### Checklist

* [ ] I wrote new tests for my new core changes.
* [ ] I have successfully ran tests, style checker and build against my new changes locally.
* [ ] I have informed the team of any breaking changes if there are any.

### CODE REVIEW

File: prover/symbolic/polyeval.go [hunk 1]
```diff
@@ -52,6 +52,11 @@ func NewPolyEval(x *Expression, coeffs []*Expression) *Expression {
 	}
 }
 
+// Name outputs the name for the PolyEval [Operator].
+func (PolyEval) Name() string {
```
Comment (AlexandreBelling) [inline prover/symbolic/polyeval.go]: You can use `reflect.TypeOf(o).String()` or `fmt.Printf("typeName=%T", o)`

**Review by AlexandreBelling — DISMISSED** [review]

**Review by gusiri — DISMISSED** [review]

**Review by gusiri — APPROVED** [review]

**Review by arijitdutta67 — APPROVED** [review]

**Review by AlexandreBelling — APPROVED** [review]
